### ISSUE TITLE
Link to maintained version

### ISSUE THREAD

**Issue by juanibiapina** [dominikh/tmux-ruby#13]
Why not link to https://github.com/nightscape/tmux-ruby, since it works properly?

**Comment by dominikh** [comment]
For one, I wasn't aware of it. On the other hand, its last commit was in December 2012, and it looks almost identical to my original version, so I'm not sure it really "works properly".

The author fixed some regexps, but there's a lot more functionality in tmux that changed. Options that were removed or changed behaviour, and so on. So in my opinion, that fork is as unmaintained as my version.

**Comment by juanibiapina** [comment]
It works in tmux 2.0.

**Comment by dominikh** [comment]
Some of its methods might work (in particular the more basic ones), some of them might fail. I know for a fact that tmux removed a number of flags and commands, and said fork doesn't address that.

Either way, it's not a maintained fork. If it works for your requirements, that's great, but it's not a maintained alternative to this project; it's just an unmaintained fork.
